### ISSUE TITLE
Implementation for private genome database

### ISSUE THREAD

**Issue by kostasgalexiou** [noefp/easy_gdb#2]
Hi,

I am configuring easy_gdb for my species (a great platform, by the way!!) and would like to have it as a private database. I have generated the file .htpasswd and have added a user with a username and a password. How can I verify the privacy of the database? I would expect that, in order to access it, I would have to add my username and password at some point.

Thanks in advance,
Kostas Alexiou

**Comment by noefp** [comment]
Hello Kostas,

If you are installing it in a server or a local linux machine with apache, you would have to edit the apache configuration file:

    vim /etc/apache2/sites-enabled/000-default.conf

and then, uncomment the next lines:

        <Directory "/var/www/html">
             AuthType Basic
             AuthName "Restricted Content"
             AuthUserFile /etc/apache2/.htpasswd
             Require valid-user
        </Directory>

Then save and close the file. You have to be certain that when you generated the .htpasswd, it was saved in the same path as the one included in the configuration file:

    htpasswd -c /etc/apache2/.htpasswd UserName

and at the end of the process you will need to restart apache, so the changes have effect:

    /etc/init.d/apache2 reload

You might need to use sudo to run those commands in a server. After this step you should see the authentication popup when reloading the web browser. Additionally, you could change the path in the directory to control which pages are private and wich ones are publicly accessible, you could also add several Directory blocks, and you could change the message in the AuthName line.

Alternatively, **if you are using Docker**, you will have to run those commands inside your Docker implementation by running first the next command in the easyGDB_docker path:

    docker-compose exec easy_gdb /bin/bash

Then you can run all the commands mentioned above.

Thank you for using easyGDB. Please, let me know if you are able to implement the password authentication and do not hesitate to contact me again here or by email.

**Comment by kostasgalexiou** [comment]
Hi Noé,

Thanks for your help. I have uncommented the corresponding code in the apache configuration file inside the docker container. The authentication pop window is now appearing nice and clear.

The corresponding information present in the README file (https://github.com/noefp/easy_gdb#private-application) is pointing to go to the easy_gdb_apache.conf and uncomment the `<Directory></Directory>` code patch present there. However, the code was already uncommented and, since I was not getting the popo window, does this suggest that the file is not overwriting the apache configuration settings?

Best,
Kostas
